### ISSUE TITLE
Search and filtering doc - add users search section

### ISSUE THREAD

**Issue by thompiler** [airbrake/airbrake-docs#105]
We recently added the ability to search for errors by the affected user's email. We should describe this in our [search and filtering doc](https://airbrake.io/docs/airbrake-faq/how-do-i-use-search-and-filtering/)

**Comment by thompiler** [comment]
Screenshots of recent feature addition:

<img width="465" alt="screen shot 2017-03-15 at 11 40 32 am" src="https://cloud.githubusercontent.com/assets/2172513/23965168/5e29dfaa-0974-11e7-8558-cfe1cb35c2d9.png">
<img width="466" alt="screen shot 2017-03-15 at 11 41 08 am" src="https://cloud.githubusercontent.com/assets/2172513/23965171/5f98d800-0974-11e7-9a86-e447b976c544.png">

**Comment by stuartm1023** [comment]
It looks like we've added quite a bit more search features. On the current page I've just described them without showing examples (I think they're pretty easy to figure out). Should I just update the screenshot and add the additional descriptions?

<img width="478" alt="screen shot 2017-09-14 at 2 05 59 pm" src="https://user-images.githubusercontent.com/31705693/30456177-7065d0f2-9957-11e7-92e4-f761fefecc83.png">

**Comment by thompiler** [comment]
>It looks like we've added quite a bit more search features. On the current page I've just described them without showing examples (I think they're pretty easy to figure out). Should I just update the screenshot and add the additional descriptions?

Sure, I think that's fine to not show a screenshot with all of possible search items. A list is fine.

Some things missing in [the list in the doc](https://airbrake.io/docs/airbrake-faq/how-do-i-use-search-and-filtering/#advanced-filtering):
- Function
- Version
- User country
- Remote country
- URL

**Comment by thompiler** [comment]
This issue has been resolved. The search doc does feature a user search description and screenshot now:

https://airbrake.io/docs/airbrake-faq/how-do-i-use-search-and-filtering/#filtering-by-custom-attributes
