### ISSUE TITLE
Add IP whitelist info to JIRA integration doc

### ISSUE THREAD

**Issue by stuartmoore1023** [airbrake/airbrake-docs#107]
# What

Add troubleshooting section to JIRA doc about whitelisting Airbrake's IPs and checking for redirect rules in customer firewall.

**Comment by stuartmoore1023** [comment]
Should we mention this as a solution to the 302 error specifically or make it a general step for troubleshooting?

**Comment by shifi** [comment]
I would just make it a general step for troubleshooting.

**Comment by stuartmoore1023** [comment]
Closed by #109
