### ISSUE TITLE
Make changes for new nav

### ISSUE THREAD

**Issue by stuartmoore1023** [airbrake/airbrake-docs#110]
# What

Make the following changes to images on these pages based on new Airbrake navigation.

- [x] https://airbrake.io/docs/integrations/bitbucket/
- settings_cog.png
- bitbucket_auth.png
- bitbucket_settings.png

- [x] https://airbrake.io/docs/integrations/campfire/
- campfire_settings.png
- campfire_testing.png

- [ ] https://airbrake.io/docs/integrations/github-enterprise/
- github_integration_type.png
- github_enterprise_repo_url.png

- [ ] https://airbrake.io/docs/integrations/github/
- github_auth.png
- github_repo_url.png

- [ ] https://airbrake.io/docs/integrations/gitlab/
- gitlab_adding_token.png
- gitlab_adding_repo_url.png

- [x] https://airbrake.io/docs/integrations/lighthouse/
- lighthouse_token_settings.png
- lighthouse_settings.png

- [x] https://airbrake.io/docs/integrations/slack/
- slack_settings_in_airbrake.png

- [x] https://airbrake.io/docs/integrations/trello/
- trello_auth.png
- trello_settings.png

- [x] https://airbrake.io/docs/airbrake-faq/configuring-notifications/
- dropdown_settings.png

- [x] https://airbrake.io/docs/airbrake-faq/configuring-project-environments/
- project_environments.png - just edit image

- [x] https://airbrake.io/docs/airbrake-faq/how-do-distinct-error-types-work/
- settings_cog.png
- distinct_grouping.png - just edit image

- [x] https://airbrake.io/docs/airbrake-faq/how-do-global-error-types-work/
- settings_cog.png
- global_grouping.png - just edit image

- [x] https://airbrake.io/docs/airbrake-faq/what-is-my-subdomain/
- subdomain_url.png
- subdomain_settings.png

- [x] https://airbrake.io/docs/airbrake-android-ios/app-versions/
- settings_cog.png

- [x] https://airbrake.io/docs/billing/account-cancelation/
- cancel_account.png

- [x] https://airbrake.io/docs/billing/update-credit-card-information/
- credit_card_edit.png - do we need an image here?

- [x] https://airbrake.io/docs/billing/updating-your-billing-info/
- billing_settings.png

**Comment by stuartmoore1023** [comment]
I need to look at the GitHub login to make sure it's all correct

**Comment by Trixi1977** [comment]
[(External) Box Governance Datasheet.pdf](https://github.com/airbrake/airbrake-docs/files/1423783/External.Box.Governance.Datasheet.pdf)

**Comment by stuartmoore1023** [comment]
I believe the Git___ pages are OK.
