### ISSUE TITLE
Add doc for new GitHub login feature

### ISSUE THREAD

**Issue by thompiler** [airbrake/airbrake-docs#117]
We now allow users to link their Airbrake account to their GitHub account. When enabled, an Airbrake user can log in by authorizing with GitHub.

The option is under a the profile settings:
<img width="332" alt="screen shot 2017-05-03 at 11 02 04 am" src="https://cloud.githubusercontent.com/assets/2172513/25674534/0242ed10-2ff0-11e7-9ee9-359eb7dca297.png">

<img width="445" alt="screen shot 2017-05-03 at 11 01 48 am" src="https://cloud.githubusercontent.com/assets/2172513/25674546/0f611bca-2ff0-11e7-9c54-4768581d1faa.png">

After enabled, users can log in using GitHub auth.
<img width="497" alt="screen shot 2017-05-03 at 11 02 23 am" src="https://cloud.githubusercontent.com/assets/2172513/25674549/1089e054-2ff0-11e7-8f38-b84abd63f800.png">

**Comment by shifi** [comment]
Just FYI: They can also enable GitHub logins from login page.

There are two ways:
- from profile page
- from login page

**Comment by thompiler** [comment]
Good point @shifi. Thanks. Users can select the "Sign in with GitHub" button to enable it from the login page by following the steps to link their GitHub account to their Airbrake account.
