### ISSUE TITLE
RE: /airbrake-faq/configuring-error-grouping-settings

### ISSUE THREAD

**Issue by maryamklabib** [airbrake/airbrake-docs#120]
It would be great if we could see examples of the format of the groupings. For example, how does one provide the error class as well as the error message? Should they be in strings or comma seperated?

Example error: 

> Mysql2::Error: MySQL server has gone away

**Comment by thompiler** [comment]
Howdy @maryamklabib thanks for the question. I've added a PR to show more explicitly how to use these grouping settings to the "Configuring error grouping settings" doc.

>It would be great if we could see examples of the format of the groupings. For example, how does one provide the error class as well as the error message? Should they be in strings or comma seperated?

The grouping settings use **error type** so given your example error, you would enter `Mysql2::Error` to your chosen grouping setting textbox in your project settings page. 

Error types listed there can be separated by spaces, commas, or newlines although Airbrake will convert all of them to newlines if you refresh the page.
