### ISSUE TITLE
RE: /airbrake-faq/deploy-tracking

### ISSUE THREAD

**Issue by ivar** [airbrake/airbrake-docs#128]
I ❤️  deploy tracking and automatic marking tickets as resolved. I also use the Pivotal Tracker integration to automatically create stories in PT.  So far, so good. 

The issue is when the following sequence occurs:

1. Error occurs
2. PT story is created
3. Work is started on PT story
4. A deploy goes up and error is marked as resolved
5. Error reoccurs
6. .. the status of the story in PT is updated in two ways:
    1. a comment is added the story that the error has reoccured (awesome!)
    2. the status of the story is marked as unstarted (very bad)

Is there a way to configure the deploy tracking / PT integration to NOT reset the story status when an error reoccurs?

**Comment by mmcdaris** [comment]
Hi @ivar,
I'm glad you making good use of deploy tracking.
Thanks for getting in touch about this issue and describing it so well 👍

I tried unchecking the PT integration setting for "Re-open accepted, delivered or finished Pivotal story when a resolved error re-occurs" and re-triggering an error.
Unchecking that option does stop the status change on the story, however it also stops the comment activity.

I don't think it's currently possible to allow the comment but stop the state change on the PT story. 
I'll ask our integration expert if it's possible to change the behavior or add another config option.

**Comment by mmcdaris** [comment]
Hi @ivar, I've submitted an internal feature request on our side for consideration. I'm gonna close this one out, but we will let you know if there is any activity on your feature request.

Thanks again for the feedback!
