### ISSUE TITLE
RE: /integrations/pivotal-tracker

### ISSUE THREAD

**Issue by morristhai** [airbrake/airbrake-docs#162]
How can I integrate the same Airbrake project with two different Pivotal Tracker projects?

**Comment by stuartmoore1023** [comment]
This seems to be a support request and is almost 2 years old.

**Comment by thompiler** [comment]
Hi @morristhai,

Sorry for the big delay in addressing your question. This is currently not supported but if you let us know more about how you would want this to work, we could add a feature request for it.
