### ISSUE TITLE
RE: /airbrake-faq/configuring-error-grouping-settings

### ISSUE THREAD

**Issue by JustAHappyKid** [airbrake/airbrake-docs#164]
How can I force a "re-grouping" of already-logged errors?

For example, I have three separate "groupings" under the default settings, all for exception `SomeError`. Suppose I then set `SomeError` to be grouped "globally", as [described in the docs](https://airbrake.io/docs/airbrake-faq/how-do-global-error-types-work/)... How can I get the three, aforementioned separate groupings to be "re-grouped" and appear together?

**Comment by stuartmoore1023** [comment]
Currently there's no way to re-group previously logged errors. You can use our search to find errors according to various parameters. All future errors would be grouped according to the new rules.

We can create a feature request for this if you'd like.
