### ISSUE TITLE
Add info on how to delete and mute errors

### ISSUE THREAD

**Issue by thompiler** [airbrake/airbrake-docs#178]
Users can now delete and mute errors through the dashboard UI. We should add a doc or section that mentions this.

Screenshot of UI:

![screen shot 2017-11-30 at 4 05 20 pm](https://user-images.githubusercontent.com/2172513/33463291-988d2c52-d5f1-11e7-9ec7-85f2231be323.png)

When an error is muted:

![screen shot 2017-11-30 at 5 14 11 pm](https://user-images.githubusercontent.com/2172513/33463385-43f67184-d5f2-11e7-905b-9e7a371da9e8.png)

**Comment by stuartmoore1023** [comment]
@thompiler if an error is deleted does it stop showing in the UI after that or does it just remove that notification of the error?

**Comment by thompiler** [comment]
>@thompiler if an error is deleted does it stop showing in the UI after that or does it just remove that notification of the error?

It does remove the error from the UI because the error is permanently deleted.

**Comment by stuartmoore1023** [comment]
@thompiler does it prevent the error from showing up again?

**Comment by thompiler** [comment]
>@thompiler does it prevent the error from showing up again?

No, if a new occurrence of that error is sent to Airbrake, it will be treated as a new error.

If the user wants to stop an error from ever showing up again, they can filter it before it's sent. This is done in the notifier config:
- Ruby and Rails can use `add_filter`: https://github.com/airbrake/airbrake-ruby#airbrakeadd_filter
- JavaScript can use `addFilter`: https://github.com/airbrake/airbrake-js#filtering-errors
- https://github.com/airbrake/phpbrake#ignoring-specific-exceptions
- https://github.com/airbrake/gobrake#ignoring-notices
- https://github.com/airbrake/SharpBrake#addfilter
- etc

**Comment by stuartmoore1023** [comment]
Completed doc. Added to Airbrake Features.
