### ISSUE TITLE
RE: /integrations/pivotal-tracker

### ISSUE THREAD

**Issue by josephgrossberg** [airbrake/airbrake-docs#179]
Is there any way to customize the subject lines of the stories created by [the Airbrake - Pivotal Tracker integration](https://airbrake.io/docs/integrations/pivotal-tracker/)?

Specifically, we get ones that say things like:

`[Airbrake] [Production] Couldn't find Schedule with 'id'=undefined`

However, we'd prefer the *project name* to the *environment name*:

`[Airbrake] [Scheduler API] Couldn't find Schedule with 'id'=undefined`

Thanks!

**Comment by thompiler** [comment]
Howdy @josephgrossberg, 

Currently, we don't support customizing the story names like this but I can make a feature request for you. One question though, why is project name important to you? Is it because you have multiple Airbrake projects connected to one Pivotal Tracker project?

**Comment by josephgrossberg** [comment]
Yes that is correct -- we have multiple Airbrake projects on one Pivotal Tracker project.

And because Pivotal Tracker provides this view by default:

<img width="379" alt="screen shot 2017-12-01 at 5 23 18 pm" src="https://user-images.githubusercontent.com/1637/33510046-5e4b83ba-d6bc-11e7-8b4c-c31e8cd04572.png">

It's harder to quickly assess bugs at a glance, than if we had project names visible:

<img width="379" alt="screen_shot_2017-12-01_at_5_23_18_pm" src="https://user-images.githubusercontent.com/1637/33510134-43ab61d2-d6bd-11e7-85c6-4f0cd33ba90d.png">

**Comment by josephgrossberg** [comment]
(Those are fictitious names.)

**Comment by thompiler** [comment]
Hey @josephgrossberg,

Yup, that clears up the use case for us. I've added your request to an internal feature request. I've also brought this up to our integration specialist. I'll let you know if they have any extra questions or info about this.

**Comment by stuartmoore1023** [comment]
Closing as this is referenced in https://github.com/airbrake/product/issues/47
