### ISSUE TITLE
RE: /airbrake-faq/what-is-a-rate-limit

### ISSUE THREAD

**Issue by SkeloGH** [airbrake/airbrake-docs#184]
The documentation covers the expected behavior on the dashboard-side of the service, however does not cover what happens server-side, like `HTTPError: 420 Client Error: status code 420` being raised once the limit has been hit.

**Comment by thompiler** [comment]
Hey @SkeloGH thanks for letting us know. If the account is rate limited, you should expect to see our API respond with: 

```
{"code":420,"type":"","message":"Too many requests in last minute - account is rate limited"}
```



We'll add a note to our API docs which you can find here: https://airbrake.io/docs/api/
