### ISSUE TITLE
Add BitBucket example post RE: /integrations/bitbucket 

### ISSUE THREAD

**Issue by mmcdaris** [airbrake/airbrake-docs#23]
An anonymous user suggested we add an example post from Airbrake to Bitbucket.

> Would be nice to see what is actually posted to bitbucket to know why this would be worth integrating.

**Comment by stuartmoore1023** [comment]
@mmcdaris is this something we should still be looking at?

**Comment by mmcdaris** [comment]
Hi @stuartmoore1023. I think it would still be helpful to have a screenshot of what the resulting BitBucket post created from an Airbrake error group looks like.
