### ISSUE TITLE
RE: /airbrake-faq/what-is-a-rate-limit

### ISSUE THREAD

**Issue by eszjay** [airbrake/airbrake-docs#244]
Could you clarify whether the rate limit distinguishes between the first occurrence of an error and subsequent occurrences? In other words, if the only occurrence of an error occurred while the rate limit was in effect, would my dashboard show that that type of error had never occurred?

**Comment by zefer** [comment]
Hi @eszjay. We make a best effort to not rate-limit previously unseen errors, but for various technical reasons (performance included), it's not guaranteed.

**Comment by thompiler** [comment]
We're marking this issue as closed but please let us know if you have any further questions.
