### ISSUE TITLE
RE: /airbrake-faq/deploy-tracking

### ISSUE THREAD

**Issue by oskarpearson** [airbrake/airbrake-docs#25]
EngineYard has changed it's variable names. https://support.cloud.engineyard.com/hc/en-us/articles/205407008-Use-Ruby-Deploy-Hooks has more info.

- environment is now config.environment_name
- current_role is now config.current_role
- revision is now config.active_revision
- repo is now config.repo
- current_path is now config.current_path

Relevant diff:
```
-  if notify_deploy_environments.include?(environment) && notify_deploy_roles.include?(current_role)
-    run "cd #{current_path} && bundle exec rake airbrake:deploy TO=#{environment} REVISION=#{revision} USER=`whoami` REPO=#{repo}"
+  if notify_deploy_environments.include?(config.environment_name) && notify_deploy_roles.include?(config.current_role)
+    run "cd #{config.current_path} && bundle exec rake airbrake:deploy TO=#{config.environment_name} REVISION=#{config.active_revision} USER=`whoami` REPO=#{config.repo}"
```

**Comment by mmcdaris** [comment]
Hi @oskarpearson! Thanks for reporting this one and including so many helpful details. 
I have updated the EngineYard example to use the new naming convention (`config.environment_name`). 
I also updated this example to use the current environment variable that the [Airbrake API expects a deploy to have](https://airbrake.io/docs/api/#deploys-v4) ( `ENVIRONMENT`, `USERNAME`,`REPOSITORY`, `REVISION`).
Please let me know if you have any further issues with the [current EngineYard example](https://airbrake.io/docs/airbrake-faq/deploy-tracking/#usage-engine-yard-cloud).
