### ISSUE TITLE
RE: /installing-airbrake/installing-airbrake-in-an-angular-2-app

### ISSUE THREAD

**Issue by toddrothe** [airbrake/airbrake-docs#274]
can i trigger an error once i'm done with these instructions? Just a quick, manual test?

**Comment by toddrothe** [comment]
You know, I tried that window.onerror() from the console yesterday but it
gave me an error saying it wasn't a thing. Tried in Chrome, safari and
opera.
I'll try the in-code version now.

**Comment by thompiler** [comment]
> You know, I tried that window.onerror() from the console yesterday but it
> gave me an error saying it wasn't a thing. Tried in Chrome, safari and
> opera.

That's odd. I just tested it before I suggested it here. That said, I was using a Javascript demo app and not specifically an Angular one. Perhaps that is why.

Let us know if you have any other questions or continued issues.

**Comment by thompiler** [comment]
I'm closing this issue @toddrothe but please let us know if you any further questions or issues either here or at support@airbrake.io.
