### ISSUE TITLE
RE: /integrations/troubleshooting-jira-issues

### ISSUE THREAD

**Issue by absynthe** [airbrake/airbrake-docs#299]
'Environment can’t be set' instructions are incomplete. In my case, the environment field was also hidden and I had to make sure I make it visible.

**Comment by stuartmoore1023** [comment]
@shifi can you confirm this? I can update the doc if needed.

**Comment by shifi** [comment]
@absynthe could you please clarify what you mean by "I had to make sure I make it visible"?

Did you have to click on the "Show" link in the field configuration page?
![hidden_environment](https://user-images.githubusercontent.com/2136477/46732415-afff4f80-cc8d-11e8-8423-eab0267874a8.png)

**Comment by stuartmoore1023** [comment]
No response. Closing.
