### ISSUE TITLE
RE: /installing-airbrake/installing-airbrake-in-a-net-application

### ISSUE THREAD

**Issue by GreenLantern4** [airbrake/airbrake-docs#308]
For .Net, I am seeing apis to create and airbrake incident.  However, are their apis to access where you can query existing airbrake incidents and the related details?

**Comment by thompiler** [comment]
Howdy @GreenLantern4 

You can find our API info in our API docs here:
https://airbrake.io/docs/api/#list-groups-v4

That's the endpoint to get a list of error groups from a project.

**Comment by thompiler** [comment]
Let us know if that doesn't answer your question or if you have any other ones.
