### ISSUE TITLE
RE: /integrations/github

### ISSUE THREAD

**Issue by shifi** [airbrake/airbrake-docs#313]
Update GitHub integration doc so it's clear that:
1. "Airbrake" access can be found/revoked in [Authorized OAuth Apps](https://github.com/settings/applications)

<img width="760" alt="p1" src="https://user-images.githubusercontent.com/2136477/47308986-12d6dc00-d5e8-11e8-9c2b-5a3f524aba89.png">

2. We only ask once for permission when authorizing unless the access is revoked on GitHub side. In that case, we ask again for the permission

**Comment by stuartmoore1023** [comment]
Closed per #338
