### ISSUE TITLE
RE: /installing-airbrake/installing-airbrake-in-a-react-app

### ISSUE THREAD

**Issue by Vanluren** [airbrake/airbrake-docs#325]
Webpack fails, because a module is missing.  The module in question is ['cross-fetch'](https://www.npmjs.com/package/cross-fetch).

**Comment by stuartmoore1023** [comment]
@vmihailenco can you verify this?

**Comment by Vanluren** [comment]
I think it was an offhand error, caused by something else. I'll close the issue for now 👍

**Comment by thompiler** [comment]
Thanks @Vanluren. Let us know if you run into any issues. You can always reach us via:
- support@airbrake.io
- chat on our docs site: https://airbrake.io/docs/
- or by opening an issue in a specific GitHub repo of ours eg: for JavaScript, it's https://github.com/airbrake/airbrake-js
