### ISSUE TITLE
RE: /features/deploy-tracking

### ISSUE THREAD

**Issue by jolim** [airbrake/airbrake-docs#326]
In the Heroku section, you reference some variables that have different default names on Heroku's Config Vars.

`PROJECT_KEY` is called `AIRBRAKE_API_KEY` 
`PROJECT_ID` is called `AIRBRAKE_PROJECT_ID`
`REPOSITORY_URL` is called (I think) `Heroku Git URL`

Not sure if it would make it easier, but this might help a new user.

**Comment by stuartmoore1023** [comment]
@shifi can you verify this?

**Comment by shifi** [comment]
Yep, so Airbrake add-on is setting `AIRBRAKE_API_KEY` & `AIRBRAKE_PROJECT_ID` but both these can be modified. I agree we should update this in our docs.

As for the `REPOSITORY_URL` it can be added and pointed to GitHub, Bitbucket, GitLab, etc:
![heroku](https://user-images.githubusercontent.com/2136477/54994451-93996a00-4fc4-11e9-9a05-6305266a3d9f.png)

**Comment by stuartmoore1023** [comment]
Closed by #335
