### ISSUE TITLE
RE: /airbrake-faq/what-triggers-a-new-email

### ISSUE THREAD

**Issue by aguynamedben** [airbrake/airbrake-docs#36]
For this part: "Error types that don’t trigger emails"

Is there a way to customize the errors that don't trigger emails? For example, if we have a known common exception that we're going to do nothing about, is there a way to still capture it in Airbrake but not send an email every time it happens after a deploy?

Examples:
- JavaScript error caused by specific version of a specific user agent
- Rate limiting errors from API providers that we know will retry if they fail

I wish we could customize the notifications a little bit more. Reducing false positives is very important.

Thanks for your help.

**Comment by thompiler** [comment]
Howdy!

There are a few things you can do in a situation like this:
1. Filter the error before it's sent to Airbrake, eg: [airbrake-js's addFilter method](https://github.com/airbrake/airbrake-js#filtering-errors)
2. Mute the error through [our API](https://airbrake.io/docs/api/#mute-group-v4)

The possible issue for your case would be neither of these options will show the error on your error dashboard so if this is a priority for you, then I can let the rest of the team know by submitting a feature request.

**Comment by aguynamedben** [comment]
Yeah, I wish I could just mute the alerts for certain errors. It would be
nice to still show errors that have been muted in the web UI, but show a
mute icon next to them and say "Ben muted this error on October 25".

The types of errors I'd like to mute are related to 404s, errors from
frequently occurring race conditions, JavaScript errors that are caused by
browser plugins, bugs, or unknown reasons, etc. I don't want to get alerts
on Saturday night for these. Not having a mute function really messes with
the signal/noise ratio for Airbrake's alerts, making us unsafely doubt the
seriousness of Airbrake errors we receive.

–Ben

**Comment by thompiler** [comment]
Hi Ben,

Thanks for the extra info about your use case.  I've submitted an internal feature request for this functionality.  

Since this is a feature request and not a specific issue or correction with our help docs, I'm going to close this issue.  If you'd like an update on this feature or have any other feature ideas, just let us know at support@airbrake.io.

**Comment by thompiler** [comment]
Hi Ben,

Could we ask for a clarification about the feature idea you had?  Would you like to see this mute feature on a project level or a user notification level?  Here's what I mean:

#### Project level
User A mutes an error and it's muted for everyone on the account.

#### User notification level
User A mutes an error and it's muted only for User A.  If other users on the account want that error muted, they need to specifically mute the error themselves.

**Comment by aguynamedben** [comment]
Good question. I think doing this at the project-level makes more sense because it prompts the team to agree on what errors are acceptable to mute. It could get a bit dangerous if individual developers were able to mute errors that annoyed them. For example, a back-end engineer could start muting front-end bugs, which might not be a great idea.

Either could work though.

FWIW I think Sentry supports this: https://twitter.com/getsentry/status/321835469958696960

**Comment by thompiler** [comment]
Thanks for the explaining how you'd imagine using this feature.  I've let the team know.

Let us know if you have any other questions or issues at support@airbrake.io.
