### ISSUE TITLE
Update links to airbrake-js

### ISSUE THREAD

**Issue by thompiler** [airbrake/airbrake-docs#360]
Now that we've split [airbrake-js](https://github.com/airbrake/airbrake-js) into browser and Node packages, the readme is in a different place. Because of this, we should update any links to airbrake-js.

For example:
https://github.com/airbrake/airbrake-js#filtering-errors

Should be updated to:
https://github.com/airbrake/airbrake-js/tree/master/packages/airbrake-js#filtering-errors

**Comment by thompiler** [comment]
@vmihailenco can you confirm that this is what we should be updating any links to? I was pretty 
sure but just wanted to double check:

> 
> For example:
> https://github.com/airbrake/airbrake-js#filtering-errors
> 
> Should be updated to:
> https://github.com/airbrake/airbrake-js/tree/master/packages/airbrake-js#filtering-errors

**Comment by vmihailenco** [comment]
Yes, please note that Node.js specific examples are moved to https://github.com/airbrake/airbrake-js/tree/master/packages/node/examples.

**Comment by stuartmoore1023** [comment]
@thompiler this appears to be fixed. Is that correct?

**Comment by thompiler** [comment]
>@thompiler this appears to be fixed. Is that correct?

This is not fixed. 

### Example

- Go to this page and click link like "Add custom parameters"
- Observe that page shown has no content about adding custom parameters

Expectation: "Add custom parameters" would lead page with info about using addFilter. Ie this doc: https://github.com/airbrake/airbrake-js/tree/master/packages/airbrake-js#filtering-errors

This is what I was describing in the original issue description:

> 
> For example:
> https://github.com/airbrake/airbrake-js#filtering-errors
> 
> Should be updated to:
> https://github.com/airbrake/airbrake-js/tree/master/packages/airbrake-js#filtering-errors

via https://github.com/airbrake/airbrake-docs/issues/360#issue-478062216


Vlad was just mentioning that links to specific examples have also been moved and depending on whether the example was backend vs frontend, it would be in a different package. eg: node examples are in the node package:
https://github.com/airbrake/airbrake-js/tree/master/packages/node/examples

Frontend examples are in the frontend package:
https://github.com/airbrake/airbrake-js/tree/master/packages/airbrake-js/examples

**Comment by stuartmoore1023** [comment]
Closed by #365

**Comment by stuartmoore1023** [comment]
Opened #376 to fix a broken link.

**Comment by thompiler** [comment]
There are still these docs that have links that need to be updated:
- https://github.com/airbrake/airbrake-docs/blob/master/jekyll/_docs/installing-airbrake/installing-airbrake-in-a-hapijs-app.md
- https://github.com/airbrake/airbrake-docs/blob/master/jekyll/_docs/installing-airbrake/installing-airbrake-in-a-bower-app.md
- https://github.com/airbrake/airbrake-docs/blob/master/jekyll/_docs/installing-airbrake/installing-airbrake-in-a-browserify-app.md
- https://github.com/airbrake/airbrake-docs/blob/master/jekyll/_docs/installing-airbrake/installing-airbrake-in-a-requirejs-app.md
- https://github.com/airbrake/airbrake-docs/blob/master/jekyll/_docs/installing-airbrake/installing-airbrake-in-an-express-app.md
- https://github.com/airbrake/airbrake-docs/blob/master/jekyll/_docs/installing-airbrake/installing-airbrake-in-a-javascript-application.md

**Comment by stuartmoore1023** [comment]
For:

 https://github.com/airbrake/airbrake-docs/blob/master/jekyll/_docs/installing-airbrake/installing-airbrake-in-a-hapijs-app.md 

It looks like hapi support has been removed per:

https://github.com/airbrake/airbrake-js/blob/010bf2037c30e578bce203620ae77a9fbdade96a/packages/browser/CHANGELOG.md#v200-wip

Should I just remove the doc or take out the link to the example?

**Comment by thompiler** [comment]
More docs that need to be updated (with line numbers):

[jekyll/_includes/airbrake-js-going-further.md
](https://github.com/airbrake/airbrake-docs/blob/master/jekyll/_includes/airbrake-js-going-further.md)
```
6:- [adding extra details to errors](https://github.com/airbrake/airbrake-js#notice-annotations)
7:- [sourcemaps for easy to parse backtraces](https://github.com/airbrake/airbrake-js#source-map)
8:- [filtering errors](https://github.com/airbrake/airbrake-js#filtering-errors)
9:- [specifying error severity](https://github.com/airbrake/airbrake-js#severity)
10:- [adding custom reporters](https://github.com/airbrake/airbrake-js#custom-reporters)
```

[jekyll/_docs/airbrake-faq/configuring-project-environments.md](https://github.com/airbrake/airbrake-docs/blob/master/jekyll/_docs/airbrake-faq/configuring-project-environments.md)
```
21:- [JavaScript](https://github.com/airbrake/airbrake-js#filtering-errors)
22:- [Angular](https://github.com/airbrake/airbrake-js#angular)
27:- [Node.js](https://github.com/airbrake/airbrake-js#filtering-errors)
```

[jekyll/_docs/features/private-sourcemaps.md](https://github.com/airbrake/airbrake-docs/blob/master/jekyll/_docs/features/private-sourcemaps.md)
```
114:We also support public sourcemaps please visit our [official airbrake-js repo](https://github.com/airbrake/airbrake-js#source-map) for more info.
```

[jekyll/_docs/integrations/logrocket.md](https://github.com/airbrake/airbrake-docs/blob/master/jekyll/_docs/integrations/logrocket.md)
```
24:[More info on using `addFilter`](https://github.com/airbrake/airbrake-js#filtering-errors)
```

[jekyll/_docs/features/breadcrumbs.md](https://github.com/airbrake/airbrake-docs/blob/master/jekyll/_docs/features/breadcrumbs.md)
```
39:[`addFilter` method](https://github.com/airbrake/airbrake-js#filtering-errors):
```

[jekyll/_docs/airbrake-faq/reducing-error-quota-usage.md](https://github.com/airbrake/airbrake-docs/blob/master/jekyll/_docs/airbrake-faq/reducing-error-quota-usage.md)
```
33:#### [Ignore errors in Javascript](https://github.com/airbrake/airbrake-js#filtering-errors)
```

**Comment by thompiler** [comment]
@stuartmoore1023 sorry, I'm not sure I understand your questions.

Here's my understanding:

I made this comment https://github.com/airbrake/airbrake-docs/issues/360#issuecomment-534736634, then you fixed the links I pointed out in https://github.com/airbrake/airbrake-docs/pull/383 and https://github.com/airbrake/airbrake-docs/pull/388. Are you asking if you actually fixed them in the PRs?

ie: timeline
1. I made this comment pointing out some more links that should be updated: https://github.com/airbrake/airbrake-docs/issues/360#issuecomment-534736634
1. You made this PR that updated the links: https://github.com/airbrake/airbrake-docs/pull/383
1. You made this comment: https://github.com/airbrake/airbrake-docs/issues/360#issuecomment-540626714
1. You made this PR that finished updating the links I pointed out in my comment: https://github.com/airbrake/airbrake-docs/pull/388

If there's any outdated links that still need to be fixed, let's fix them. If not, let's close the issue. 👍 

Feel free to ping me on Slack if that's easier too.

**Comment by stuartmoore1023** [comment]
@thompiler thanks. Closing.
