### ISSUE TITLE
Pull most recent ruby gem version

### ISSUE THREAD

**Issue by mmcdaris** [airbrake/airbrake-docs#363]
It would be neat if as part of the deploy process we pulled the most recent airbrake gem version to display in docs that rely on it like:
https://airbrake.io/docs/ruby/upgrading-your-notifier/

Another option would be to perform a request for the most recent gem version when the page is loaded.

**Comment by thompiler** [comment]
@mmcdaris now that we do not list a specific version in our docs, is this feature idea still relevant?

This is the update: https://github.com/airbrake/airbrake-docs/pull/401

**Comment by mmcdaris** [comment]
Good point @thompiler, let's close it out!
