### ISSUE TITLE
RE: /features/private-sourcemaps

### ISSUE THREAD

**Issue by abibell** [airbrake/airbrake-docs#366]
# Simplify private sourcemaps configuration
## Principle

1. Assume and enforce developers to always have filename and filename.map always. For instance app.min.js will always have a app.min.js.map
2. Rely on domain URL

## Process
1. Change **notice.context.sourceMaps** to contain just the base domain URL
2. CURL should send a zip of all .map files and domain URL

## Advantages
This eliminates the need to keep track of files. Convention over extensive configuration. Especially useful when we produce random js and css files at the end of the process

**Comment by vmihailenco** [comment]
We've implemented something similar using glob-like patterns in https://github.com/airbrake/airbrake-docs/pull/394. So instead of relying on subdomain you can provide a pattern like `**mydomain.com/**/myfile.min.js` which should be more flexible and reliable.
