### ISSUE TITLE
RE: /performance-monitoring/frequently-asked-questions

### ISSUE THREAD

**Issue by sdfreund10** [airbrake/airbrake-docs#369]
I think there is a bug in the code example on excluding performance checks for specified endpoints.
```
Airbrake.add_performance_filter do |resource|
  resource.ignore! if resource.route == %r{/health_check}
end
```

At least my application (running Rails 5.2, airbrake 9.4.3, and airbrake-ruby 4.6.0), `resource.route` returns a string, meaning the double equals comparison with a regex will _always_ return false.

Perhaps it should be one of the following?
```
%r{/health_check} === resource.route
resource.route.match? %r{/health_check}
```

Offending section: https://github.com/airbrake/airbrake-docs/blob/master/jekyll/_docs/performance-monitoring/frequently-asked-questions.md#how-can-i-prevent-a-route-from-reporting-performance

**Comment by kyrylo** [comment]
Good find, thanks! Yeah the code looks incorrect. I also updated airbrake-ruby:
https://github.com/airbrake/airbrake-ruby/commit/9c57a8b8995cadb1ef13d57847a8064c2d9d5f98
