### ISSUE TITLE
RE: /integrations/webhooks

### ISSUE THREAD

**Issue by derekgottlieb** [airbrake/airbrake-docs#38]
It would be helpful if you could include some troubleshooting tips for common webhook errors. For example, I was trying to enable a webhook to send to my TLSv1.2 server, but was getting the following error in the Airbrake UI when I click "Test integration":

`Error: SSL_connect returned=1 errno=0 state=error: certificate verify failed - Please make sure the webhook url you provided is correct.`

The way to address this was to change my webserver config to provide the full intermediate certificate chain. I would imagine there are a handful of common errors like this that could be included in the docs so people could resolve common issues themselves.

**Comment by stuartmoore1023** [comment]
closing per @shifi - We show error messages in the app.
