### ISSUE TITLE
RE: /integrations/troubleshooting-jira-issues

### ISSUE THREAD

**Issue by bmschwa** [airbrake/airbrake-docs#381]
Summary is definitely in my list of fields on the screen (both for the default and for the project specific screens page)... still getting a 400 error.

**Comment by stuartmoore1023** [comment]
Are you using the classic or next-gen JIRA?

**Comment by shifi** [comment]
@bmschwa please let us know what is the type of JIRA project you're trying to integrate with.

**Comment by thompiler** [comment]
We're going to close this issue now but please reach out to us if you have any further questions or problems getting Jira integrated with you Airbrake project.

Feel free to open another issue or email to us at support@airbrake.io.
