### ISSUE TITLE
RE: /features/private-sourcemaps

### ISSUE THREAD

**Issue by vhare** [airbrake/airbrake-docs#387]
I'm finding it difficult to debug which step I'm missing in my implementation of private source maps. It looks like I'm uploading the source map files successfully (the requests return ids and status 200s). I'm adding explicit URLs to the context. But it appears as though the association has not been successful

```json
`"sourceMapEnabled": true,
  "sourceMapErrors": {
    "https://cdn.summitlearning.org/javascripts/19-7e4ad96c.js": "http.Get url=\"https://cdn.summitlearning.org/javascripts/19-7e4ad96c.js.map\": got 403 Forbidden, expected 200 OK",
    "https://cdn.summitlearning.org/javascripts/new_relic_prod.js": "http.Get url=\"https://cdn.summitlearning.org/javascripts/new_relic_prod.map\": got 403 Forbidden, expected 200 OK"
  },
  "sourceMaps": {
    "https://cdn.summitlearning.org/javascripts/19-7e4ad96c.js": "https://cdn.summitlearning.org/javascripts/19-7e4ad96c.js.map"
  }`
```

According to documentation, if I successfully upload a file with name="https://cdn.summitlearning.org/javascripts/19-7e4ad96c.js.map" to airbrake, it should be able to find the uploaded version of https://cdn.summitlearning.org/javascripts/19-7e4ad96c.js.map to connect it the error.

One note : it would be helpful to be able to get / see the successfully uploaded source maps, as well as their names.

**Comment by vhare** [comment]
I'm using the RestClient API to make the request, but essentially looks like this:
```
response = RestClient.post(
          "https://airbrake.io/api/v4/projects/#{ENV['AIRBRAKE_PROJECT_ID']}/sourcemaps",
          {
            multipart: true,
            file: File.new(file),
            name: https://cdn.summitlearning.org/javascripts/19-7e4ad96c.js.map,
          },
          {
            Authorization: "Bearer #{ENV['AIRBRAKE_API_KEY']}",
          }
        )
```
So the https://cdn.summitlearning.org/javascripts/19-7e4ad96c.js.map is actually invalid (because I'm not uploading the source map to s3), it's just the 'name' that I'm using to upload the file to airbrake directly, and also the name that I use in the airbrake context to directly associated the .js file with its corresponding .map file.

I think it's returning a 403 instead of a 404 because without the correct permissions requests to any sort of url with the cdn.summitlearning.org is erroring out with a 403. Is the 403 the reason why airbrake is not falling back to look for the private uploaded sourcemaps? If the request returned a 404 instead (e.g. if the hostname was localhost:3000) would it work?
Just trying to reason through why the private source maps are not being found. I already know that this URL (https://cdn.summitlearning.org/javascripts/19-7e4ad96c.js.map) does not / should not exist.

**Comment by vmihailenco** [comment]
>Is the 403 the reason why airbrake is not falling back to look for the private uploaded sourcemaps? If the request returned a 404 instead (e.g. if the hostname was localhost:3000) would it work?

Before doing any HTTP requests Airbrake checks if there is a file with such name in the private sourcemaps database. Only if such file is not found in local db Airbrake will attempt to make a HTTP request. So this should work if the sourcemap was successfully uploaded.

You can check what sourcemaps you have using following API:

```
GET https://getexceptional.airbrake.io/api/v4/projects/AIRBRAKE_PROJECT_ID/sourcemaps?key=AIRBRAKE_API_KEY
```
