### ISSUE TITLE
Style code links

### ISSUE THREAD

**Issue by thompiler** [airbrake/airbrake-docs#398]
Our code styled words are not styled any differently when they are links. We should do something to indicate that they are links. eg: color, underline, etc

Here's how GitHub Markdown handles it:
- `no-link`
- [`yes-link`]()

### A link

`airbrake-python` here is actually a link. 

![Screen Shot 2019-11-08 at 5 45 56 PM](https://user-images.githubusercontent.com/2172513/68520814-d1938780-024f-11ea-976b-b70c2daf666e.png)

### Not a link

![Screen Shot 2019-11-08 at 5 46 03 PM](https://user-images.githubusercontent.com/2172513/68520816-d2c4b480-024f-11ea-9659-a2349cb0a230.png)

**Comment by stuartmoore1023** [comment]
@thompiler which page is that with the `airbrake-python` link?

**Comment by thompiler** [comment]
>@thompiler which page is that with the `airbrake-python` link?

That page is here:
https://airbrake.io/docs/performance-monitoring/updating-to-pybrake-from-deprecated-versions/

**Comment by stuartmoore1023** [comment]
@thompiler would it be changing this code?

`<code class="highlighter-rouge">` 

Do you know of any easy way to find all instances of this in the docs?

**Comment by thompiler** [comment]
@stuartmoore1023 yup, we'd have to add some different style for code tags that are also links here:

https://github.com/airbrake/airbrake-docs/blob/58edfd9dcd8b6f98f4aee8c0ff2c330cdf6e0bf6/jekyll/_sass/_syntax-highlighting.scss#L8-L10
