### ISSUE TITLE
RE: /airbrake-faq/rejected-errors

### ISSUE THREAD

**Issue by shifi** [airbrake/airbrake-docs#400]
2 broken links in [rejected errors doc](https://airbrake.io/docs/airbrake-faq/rejected-errors/):
<img width="840" alt="rejected-errors-links" src="https://user-images.githubusercontent.com/2136477/69704590-03cc3280-10f4-11ea-931a-77ebebe710cb.png">

**Comment by stuartmoore1023** [comment]
It says the XML API is deprecated and replaced by the [V3 Notifier API](https://airbrake.io/docs/api/#create-notice-v3). Should I change the XML link to that?

**Comment by thompiler** [comment]
>It says the XML API is deprecated and replaced by the [V3 Notifier API](https://airbrake.io/docs/api/#create-notice-v3). Should I change the XML link to that?

@stuartmoore1023 I don't think so. We still accept errors via the XML API, so we should probably provide API specs.

**Comment by stuartmoore1023** [comment]
Closing per #406
