### ISSUE TITLE
Update JavaScript install guides

### ISSUE THREAD

**Issue by thompiler** [airbrake/airbrake-docs#407]
## Update docs

airbrake-js has transitioned into two separate packages:
- @airbrake/browser: https://github.com/airbrake/airbrake-js/blob/master/packages/browser
- @airbrake/node: https://github.com/airbrake/airbrake-js/blob/master/packages/node

We need to update our JavaScript framework install guides to reflect this change:

- [x] https://airbrake.io/docs/installing-airbrake/installing-airbrake-in-an-angularjs-app/
- [x] https://airbrake.io/docs/installing-airbrake/installing-airbrake-in-an-express-app/
- [x] https://airbrake.io/docs/installing-airbrake/installing-airbrake-in-a-javascript-application/
- [x] https://airbrake.io/docs/installing-airbrake/installing-airbrake-in-a-node-app/
- [x] https://airbrake.io/docs/installing-airbrake/installing-airbrake-in-a-redux-app/
- [x] https://airbrake.io/docs/installing-airbrake/installing-airbrake-in-a-browserify-app/
- [x] https://airbrake.io/docs/installing-airbrake/installing-airbrake-in-an-angular-2-app/
- [x] https://airbrake.io/docs/installing-airbrake/installing-airbrake-js-in-a-rails-app/
- [x] https://airbrake.io/docs/installing-airbrake/installing-airbrake-in-a-react-app/
- [x] https://airbrake.io/docs/installing-airbrake/installing-airbrake-in-a-vuejs-app/

@mmcdaris I believe you have some sort of automated way that pulls examples from the actual airbrake-js GitHub. How does one do this?

## Remove old docs
Some frameworks are no longer supported. We should remove these docs:

- [x] https://airbrake.io/docs/installing-airbrake/installing-airbrake-in-an-ember-app/
- [x] https://airbrake.io/docs/installing-airbrake/installing-airbrake-in-a-hapijs-app/
- [x] remove bower
- [x] remove requirejs

**Comment by mmcdaris** [comment]
I've updated the fetching scripts and pulled the newest versions of the instructions. 👍, that took care of a few of the update tasks.

**Comment by thompiler** [comment]
Closing as https://github.com/airbrake/airbrake-docs/pull/410 and https://github.com/airbrake/airbrake-docs/pull/411 finished the last remaining items.
