### ISSUE TITLE
RE: /installing-airbrake/installing-airbrake-in-a-react-app

### ISSUE THREAD

**Issue by khulani** [airbrake/airbrake-docs#429]
This may not be an issue.  But for me, I had to use
```import { Notifier } from '@airbrake/browser';```
instead of 
```import { Notifier } from '@airbrake/notifier';```

Also, not sure if adding `export default` is appropriate or not.  (I'm a bit of a noob, so maybe that goes without saying).

**Comment by thompiler** [comment]
You are totally right @khulani! Thanks for catching that.
