### ISSUE TITLE
RE: /installing-airbrake/installing-airbrake-in-a-rails-application

### ISSUE THREAD

**Issue by nextekcarl** [airbrake/airbrake-docs#434]
The link at at the bottom of the page goes to a 404. I'm trying to find out if there is a config option of some kind I can put into a app.json file so review apps get Airbrake installed in review apps, but don't send error emails. I just want a place to store the error so I can see the context for each error without combing through the logs.

**Comment by thompiler** [comment]
Hey @nextekcarl thanks for pointing that out. We'll update the doc.

About what you're trying to achieve, I think I need more info. What kind of application is this? eg: Rails, JavaScript, PHP, etc

If you want to report errors to Airbrake but not get error emails sent to you, you can change your email notification settings. No extra setup would be required too, you'd just install Airbrake normally and tweak your email settings separately.

**Comment by nextekcarl** [comment]
Thanks.

It is a Rails app using the Heroku Pipeline. We have staging and production set up and sending emails currently. But Review Apps are throw away environments that are set up based upon the settings in he app.json file. What I'd like is a way to set up Airbrake:free when we set up a Review app (which happens automatically when we open a PR) but I don't want the emails to be sent out for that review app (it goes to the account that owns the Heroku Pipeline). Since it is set up automatically, the only fix I can see right now is to manually turn off emails notifications every time we open a PR and a Review app gets built as the default behavior is to send those notifications.

Are there any options we can add to the app.json file to control the notifications of a Review App when it is set up?

**Comment by thompiler** [comment]
There is no way to change your personal user notification settings via an API or our gem. The only current way is via the web interface.

I'd be happy to log it as a feature request though - let me know.

**Comment by nextekcarl** [comment]
That would be really useful, thanks for the quick response.

**Comment by thompiler** [comment]
Certainly. Please let us know if you have any other suggestions or questions. You can always reach us at support@airbrake.io.
