### ISSUE TITLE
No 404 page

### ISSUE THREAD

**Issue by zefer** [airbrake/airbrake-docs#5]
1. visit a URL that doesn't exist: https://airbrake.io/docs/installing-airbrake-in-your-application
2. observe an error, expected a friendly 404 page

![](https://api.monosnap.com/rpc/file/download?id=AuIwXRYv0bi3IbYN77G4MUWzpi9LfA)

**Comment by mmcdaris** [comment]
Thanks for catching this one @zefer, `404`'s now get routed to `/docs/`
I was able to redirect `404`'s back to `/docs/` with the following [s3 bucket routing rule](https://docs.aws.amazon.com/AmazonS3/latest/dev/HowDoIWebsiteConfiguration.html)
```xml
<RoutingRules>
    <RoutingRule>
        <Condition>
            <HttpErrorCodeReturnedEquals>404</HttpErrorCodeReturnedEquals>
        </Condition>
        <Redirect>
            <HostName>airbrake.io</HostName>
            <ReplaceKeyWith>docs/</ReplaceKeyWith>
        </Redirect>
    </RoutingRule>
</RoutingRules>
```

**Comment by phumpal** [comment]
Nice one @mmcdaris. 

Is that the appropriate behavior? Shouldn't it return the [404 page](https://airbrake.io/404.html)?

**Comment by zefer** [comment]
Thanks. That's definitely an improvement, but we should display 404 information for users, and return a 404 code for bots, browsers, etc.

**Comment by mmcdaris** [comment]
We now return our 404 page where appropriate. Closing this one out.
