### ISSUE TITLE
Out-of-date API docs

### ISSUE THREAD

**Issue by zefer** [airbrake/airbrake-docs#51]
This page https://airbrake.io/docs/api-2/notifier-api-v23/ documents our old notifier endpoint.

I suggest we:

1. Fix the broken links
1. Fix the formatting (I see lots of `<hr/>` in the rendered HTML, and overall, it looks like a page lacking attention
1. Put a notice at the top stating that this documents legacy APIs, linking to our API docs, here: https://airbrake.io/docs/api/ or directly to the notifier endpoint, here: https://airbrake.io/docs/api/#error-notification-v3
1. Check for inbound links to this page, and https://airbrake.io/docs/api-2/ and consider changing them to link to https://airbrake.io/docs/api
1. Consider removing https://airbrake.io/docs/api-2/ - why does it exist?

**Comment by donalmurtagh** [comment]
At the bottom of the page it seems there's supposed to be an example XML notice document

> Example Request and Response<hr/>
> @@@ $ cat example.xml @@@

But the actual content of the XML file isn't shown anywhere

**Comment by vmihailenco** [comment]
I suggest to remove docs for XML API. It is not supported for years and most notifiers already upgraded to JSON API.

**Comment by donalmurtagh** [comment]
The XML API is still supported, so the docs should not be removed. Even if the API was not supported the docs should be still not be removed as they would be useful to someone trying to migrated from the XML API to the new JSON API.

**Comment by thompiler** [comment]
I believe I've addressed the problems outlined in this issue in #52 but I'm unsure about one of the broken links. Where should the links leading to http://airbrake.io/airbrake_2_3.xsd point to?

**Comment by landydan** [comment]
I am using a grails Airbrake plugin that seems to be using an old version of your API, since I see that it is sending notices with XML.  Can you tell me where I can find the old documentation?

Thanks.

**Comment by thompiler** [comment]
Howdy @landydan!

You can find the documentation for our old XML API here:
https://airbrake.io/docs/legacy-xml-api/

Let us know if you have any questions.

**Comment by landydan** [comment]
Thanks, this is helpful.

My only question is one I sent to Stuart Moore at Airbrake, but perhaps you
know the answer:

-------------
It is interesting that the Java library you have available for download on
your docs page makes use of that deprecated XML format.

Is there a plan to replace the Java library with one that makes use of the
current API?
------------

**Comment by thompiler** [comment]
> My only question is one I sent to Stuart Moore at Airbrake, but perhaps you
> know the answer:
> 
>> It is interesting that the Java library you have available for download on
>> your docs page makes use of that deprecated XML format.
>> 
>> Is there a plan to replace the Java library with one that makes use of the
>> current API?

Yes, this is something we're discussing and planning internally. Let us know if you have any other questions.
