### ISSUE TITLE
RE: /installing-airbrake/installing-airbrake-in-a-php-application

### ISSUE THREAD

**Issue by mauriciovillalobos** [airbrake/airbrake-docs#69]
Hey All

While I was integrating Airbrake into a CakePHP 3.x server, I noticed that it completely takes over the default error handling that CakePHP provides.
I made a new error handler class to have both the ability to send errors to Airbrake, and also continue with the default error handling.

Here's a gist https://gist.github.com/mauriciovillalobos/01a97f9ee6179ad70b17d54f37cc5010

**Comment by thompiler** [comment]
Hi @mauriciovillalobos 

If this is an issue with our PHP notifier, can you please open a new issue in that notifier's repository?

https://github.com/airbrake/phpbrake/issues

**Comment by mauriciovillalobos** [comment]
Hi @thompiler 

Well not exactly and issue per se, this is more like a contribution for anyone integrating airbrake into a CakePHP server.
But you're right it's better to bring it up on the PHP notifier repository. I'll do that.

Thanks, you can close this now.

**Comment by thompiler** [comment]
>Well not exactly an issue per se, this is more like a contribution for anyone integrating airbrake into a CakePHP server.

Ah I see. Well, you can either create a new issue or PR in PHPbrake to add this kind of functionality to our official PHP notifier or you can create a community notifier for other Airbrake users if you'd like to keep this separate.

We list both official notifiers and community notifiers on this page here:
https://airbrake.io/languages

>Thanks, you can close this now.

Sounds good. Feel free to open another issue or write in to support@airbrake.io if you have any further issues or questions.
