### ISSUE TITLE
Add description of "enable webhook activity" option for Pivotal Tracker

### ISSUE THREAD

**Issue by thompiler** [airbrake/airbrake-docs#85]
Our Pivotal Tracker integration allows for webhook updates stored as Airbrake error comments. This option can be enabled or disabled. Here's an example of the activity recorded in the comments section of an Airbrake error:

![screen shot 2017-02-15 at 11 43 51 am](https://cloud.githubusercontent.com/assets/2172513/23003168/b75794c8-f3a3-11e6-8586-be3e116c1b82.png)

This feature and how to enable/disable it should be described in our Pivotal Tracker doc:
https://airbrake.io/docs/integrations/pivotal-tracker/

**Comment by thompiler** [comment]
Also, part of the webhook functionality is that when a Pivotal Tracker story is closed, its corresponding Airbrake error will be resolved.

**Comment by stuartmoore1023** [comment]
@thompiler can I use the screenshot you provided in the doc or do we not need one?

**Comment by thompiler** [comment]
Sorry, didn't answer this before you started the PR. I ended up switching out the image because I noticed the one I added above looks blurry or slightly lower resolution for some reason.

**Comment by thompiler** [comment]
Closed by https://github.com/airbrake/airbrake-docs/pull/86
